# ===================================================================
# Spring Boot configuration for Heroku deployment.
#
# This configuration is specifically for Heroku deployment and uses
# environment variables for sensitive data.
# ===================================================================

logging:
  level:
    ROOT: INFO
    tech.jhipster: INFO
    com.nextjstemplate: INFO

management:
  prometheus:
    metrics:
      export:
        enabled: false

spring:
  devtools:
    restart:
      enabled: false
    livereload:
      enabled: false
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: ${DATABASE_URL}
    hikari:
      poolName: Hikari
      auto-commit: false
      maximum-pool-size: 2
      # LOB-optimized connection pool settings
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 60000
      validation-timeout: 5000
      connection-test-query: SELECT 1
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate.jdbc.time_zone: UTC
      hibernate.id.new_generator_mappings: true
      hibernate.connection.provider_disables_autocommit: true
      hibernate.cache.use_second_level_cache: true
      hibernate.cache.use_query_cache: false
      hibernate.generate_statistics: false
      hibernate.jdbc.batch_size: 25
      hibernate.order_inserts: true
      hibernate.order_updates: true
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
      # Modern LOB configuration for Hibernate 6.x
      hibernate.jdbc.lob.non_contextual_creation: true
      hibernate.jdbc.lob.fetch_size: 0
      hibernate.jdbc.lob.force_streams: false
      # Connection settings for LOB handling
      hibernate.connection.charSet: UTF-8
      hibernate.connection.characterEncoding: UTF-8
      hibernate.connection.useUnicode: true
      # Additional settings for LOB handling
      hibernate.jdbc.batch_versioned_data: true
      hibernate.batch_fetch_style: DYNAMIC
  liquibase:
    enabled: true
    contexts: prod
  thymeleaf:
    cache: true

server:
  port: ${PORT:8080}
  shutdown: graceful
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json,image/svg+xml
    min-response-size: 1024

# ===================================================================
# JHipster specific properties
# ===================================================================

jhipster:
  http:
    cache:
      timeToLiveInDays: 1461
  cache:
    ehcache:
      time-to-live-seconds: 3600
      max-entries: 1000
  security:
    authentication:
      jwt:
        # Use environment variable for JWT secret in production
        base64-secret: ${JHIPSTER_JWT_SECRET:OTBjY2UxOWE1NjI4YWU4ZmJkZjliNzYwOTBiM2Y3MmJkMzRlZGVhNTE0MDFjNWZkZTM4MDk4MzkxZmEzMDg3NzEzMTk3YjZiYTVhNTAzZmE0NjQ5ODFjMjcyYTIxOTZiMGQ4ZDE5ODIwMTI1Yzk2YjMzNmY4ZDdkM2U4Mzk0MWU=}
        token-validity-in-seconds: 86400
        token-validity-in-seconds-for-remember-me: 2592000
  logging:
    use-json-format: false
    logstash:
      enabled: false
      host: localhost
      port: 5000
      ring-buffer-size: 512
